"""Build 2025 expectation curves from real CBS weekly data.

Loads weekly stat lines for all positions (DST, K, RB, TQB, WR), builds
expectation curves via sffl.calibrate.build_curves(), and writes the result
to calibration/2025.yaml with provenance metadata.

Input: data/weekly/2025/{DST,K,RB,TQB,WR}.csv (gitignored, real CBS data)
Output: calibration/2025.yaml (generated, derived data)
"""

import os
import sys
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from sffl.league import load_league                  # noqa: E402
from sffl.weekly import load_weekly                  # noqa: E402
from sffl.calibrate import build_curves, save_curves  # noqa: E402

# Explicit constants at top
LEAGUE_PROFILE_PATH = os.path.join(os.path.dirname(__file__), "..",
                                   "leagues", "sffl", "2026.yaml")
WEEKLY_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "weekly", "2025")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "calibration", "2025.yaml")

POSITIONS = ["DST", "K", "RB", "TQB", "WR"]
SEASON = 2025


def load_all_weekly(data_dir, positions):
    """Load and concatenate weekly data for all positions."""
    all_lines = []
    for pos in positions:
        path = os.path.join(data_dir, f"{pos}.csv")
        lines = load_weekly(path)
        all_lines.extend(lines)
    return all_lines


def main():
    # Load league profile
    lg = load_league(LEAGUE_PROFILE_PATH)

    # Load and concatenate all weekly data
    lines = load_all_weekly(WEEKLY_DATA_DIR, POSITIONS)

    # Count distinct players and total player-weeks
    player_ids = Counter(ln.player_id for ln in lines)
    num_distinct_players = len(player_ids)
    num_player_weeks = len(lines)

    # Build curves
    curves = build_curves(lg, lines)

    # Write the curves through the same serializer production code uses, so
    # the two can never drift. No timestamp in the header - re-running the
    # generator against the same weekly data must produce a byte-identical
    # file, not a timestamp-only diff on every run.
    header_lines = [
        "# Generated expectation curves from 2025 weekly data",
        f"# Source: {SEASON} CBS weekly stat lines (DST, K, RB, TQB, WR)",
        "# Generated by: poc/build_calibration.py",
        f"# Data: {num_distinct_players} distinct players, {num_player_weeks} player-weeks",
        "",
    ]

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    save_curves(curves, OUTPUT_PATH)
    with open(OUTPUT_PATH) as fh:
        body = fh.read()
    with open(OUTPUT_PATH, "w") as fh:
        fh.write("\n".join(header_lines) + "\n")
        fh.write(body)

    # Print summary
    print(f"Loaded {num_player_weeks} player-weeks from {num_distinct_players} distinct players")
    print("\nBanded stat curve points by stat:")
    for stat in sorted(curves.keys()):
        num_points = len(curves[stat])
        print(f"  {stat:12s}: {num_points:3d} points")

    print(f"\nWrote curves to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
